env: "local"
http:
  port: ":3000"
  readTimeout: 5s
  writeTimeout: 5s
  maxHeaderBytes: 1024
postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "qwerty"
  database: "postgres"
  sslmode: "disable"
