// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package ref

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type schemaMigrationsTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *schemaMigrationsTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("schema_migrations").
func (v *schemaMigrationsTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *schemaMigrationsTableType) Columns() []string {
	return []string{
		"version",
		"dirty",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *schemaMigrationsTableType) NewStruct() reform.Struct {
	return new(SchemaMigrations)
}

// NewRecord makes a new record for that table.
func (v *schemaMigrationsTableType) NewRecord() reform.Record {
	return new(SchemaMigrations)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *schemaMigrationsTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// SchemaMigrationsTable represents schema_migrations view or table in SQL database.
var SchemaMigrationsTable = &schemaMigrationsTableType{
	s: parse.StructInfo{
		Type:    "SchemaMigrations",
		SQLName: "schema_migrations",
		Fields: []parse.FieldInfo{
			{Name: "Version", Type: "int64", Column: "version"},
			{Name: "Dirty", Type: "bool", Column: "dirty"},
		},
		PKFieldIndex: 0,
	},
	z: new(SchemaMigrations).Values(),
}

// String returns a string representation of this struct or record.
func (s SchemaMigrations) String() string {
	res := make([]string, 2)
	res[0] = "Version: " + reform.Inspect(s.Version, true)
	res[1] = "Dirty: " + reform.Inspect(s.Dirty, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *SchemaMigrations) Values() []interface{} {
	return []interface{}{
		s.Version,
		s.Dirty,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *SchemaMigrations) Pointers() []interface{} {
	return []interface{}{
		&s.Version,
		&s.Dirty,
	}
}

// View returns View object for that struct.
func (s *SchemaMigrations) View() reform.View {
	return SchemaMigrationsTable
}

// Table returns Table object for that record.
func (s *SchemaMigrations) Table() reform.Table {
	return SchemaMigrationsTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *SchemaMigrations) PKValue() interface{} {
	return s.Version
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *SchemaMigrations) PKPointer() interface{} {
	return &s.Version
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *SchemaMigrations) HasPK() bool {
	return s.Version != SchemaMigrationsTable.z[SchemaMigrationsTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.Version = pk.
func (s *SchemaMigrations) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = SchemaMigrationsTable
	_ reform.Struct = (*SchemaMigrations)(nil)
	_ reform.Table  = SchemaMigrationsTable
	_ reform.Record = (*SchemaMigrations)(nil)
	_ fmt.Stringer  = (*SchemaMigrations)(nil)
)

func init() {
	parse.AssertUpToDate(&SchemaMigrationsTable.s, new(SchemaMigrations))
}
